### ISSUE TITLE
parser 설계 및 준비

### ISSUE THREAD

**Issue by brixxt27** [Arkingco/42_minishell#15]
### TODO
- [x] (insjang) cd 는 인자를 다르게 받는다는 것 제대로 알아오기
- [x] 디렉토리 별로 관리 할 수 있도록 Makefile 작성
- [x] grammer.md file_path -> exec_path 로 변경 이슈 해결 후 닫기
- [x] parser.c 설계
- [x] EBNF 문법 공부
- [x] 문법 예외 확인
- [x] git issue convention 정리

**Comment by brixxt27** [comment]
pipe 는 stream 으로 fd 를 할당 받아 사용할 수 있다.

**Comment by brixxt27** [comment]
cd "" 를 하면 제자리로 이동하며 oldpwd 가 현재 위치로 변경된다.

**Comment by brixxt27** [comment]
Makefile 은 천천히 공부해서 작성할 예정입니다
