### ISSUE TITLE
minishell 이슈 list

### ISSUE THREAD

**Issue by brixxt27** [Arkingco/42_minishell#81]
### TODO
- [x] [malloc :](malloc: Invalid argument) : execution 에서 일어남
- [x] ctrl + \ ignore 해결
- [x] PATH= 가 존재하지 않을 때 SIGSEGV

**Comment by brixxt27** [comment]
ctrl + \ 일 때 readline 에 들어온 것을 버퍼로 넣지 않고, 무시하도록 하여 없앴다. 무시하지 않고 다시 찍도록 만들면 표준 입력을 기다리는 cmd 등 자식 프로세스를 만들 때 출력에 문제가 생긴다.
